// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
function buildSupabaseUrl(rawUrl, projectId) {
    const normalizedFromUrl = rawUrl?.replace(/\/rest\/v1\/?$/, '').replace(/\/$/, '');
    if (normalizedFromUrl)
        return normalizedFromUrl;
    if (projectId)
        return `https://${projectId}.supabase.co`;
    return '';
}
function createSupabaseClient() {
    // Client-side must use VITE_* values only to avoid stale/mismatched host resolution.
    const SUPABASE_PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID;
    const SUPABASE_URL = buildSupabaseUrl(import.meta.env.VITE_SUPABASE_URL, SUPABASE_PROJECT_ID);
    const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
        throw new Error('Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY (or VITE_ prefixed versions) are set in your .env file.');
    }
    return {
        client: createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
            auth: {
                storage: typeof window !== 'undefined' ? localStorage : undefined,
                persistSession: true,
                autoRefreshToken: true,
            }
        }),
        signature: `${SUPABASE_URL}::${SUPABASE_PUBLISHABLE_KEY}`,
    };
}
let _supabase;
let _signature = '';
function getSupabaseClient() {
    const { client, signature } = createSupabaseClient();
    if (!_supabase || _signature !== signature) {
        _supabase = client;
        _signature = signature;
    }
    return _supabase;
}
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({}, {
    get(_, prop, receiver) {
        const current = getSupabaseClient();
        return Reflect.get(current, prop, receiver);
    },
});
